version: '3'
services:
  redis:
    container_name: "redis"
    image: "redis:3.0.6-alpine"
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - ./../../../../../../data:/data
  blazegraph:
    build:
      args:
        WHYIS_IMAGE_TAG: ${WHYIS_IMAGE_TAG:-latest}
      context: ../../../..
      dockerfile: docker/image/whyis-blazegraph/Dockerfile
    container_name: "blazegraph"
    image: tetherlessworld/whyis-blazegraph:${WHYIS_IMAGE_TAG:-latest}
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - ./../../../../../../data:/data
